### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
import tensorflow as tf 
print ('we are using tensorflow version',tf.__version__)

we are using tensorflow version 2.0.0


#### Collect Fashion mnist data from tf.keras.datasets 

In [2]:
(trainX, trainY),(testX, testY) = tf.keras.datasets.fashion_mnist.load_data()

In [3]:
print ('traing set shape',trainX.shape)
print ('training set shape',trainY.shape)
print ('test set shape',testX.shape)
print ('test set shape',testY.shape)

traing set shape (60000, 28, 28)
training set shape (60000,)
test set shape (10000, 28, 28)
test set shape (10000,)


#### Change train and test labels into one-hot vectors

In [4]:
#Convert labels to one hot encoding
train = tf.keras.utils.to_categorical(trainY, num_classes=10)
test = tf.keras.utils.to_categorical(testY, num_classes=10)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [5]:
tf.keras.backend.clear_session()
#Initialize model, reshape & normalize data
model = tf.keras.models.Sequential()

#Reshape data from 2D (28,28) to 3D (28, 28, 1)
model.add(tf.keras.layers.Reshape((28,28,1),input_shape=(28,28,)))

#normalize data
model.add(tf.keras.layers.BatchNormalization())

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [6]:
#Add first convolutional layer
model.add(tf.keras.layers.Conv2D(32, #Number of filters 
                                 kernel_size=(3,3), #Size of the filter
                                 activation='relu'))

#Add second convolutional layer
model.add(tf.keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))

#Add MaxPooling layer
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))

#Flatten the output
model.add(tf.keras.layers.Flatten())

#Dense layer
model.add(tf.keras.layers.Dense(200, activation='relu'))

model.add(tf.keras.layers.Dense(100, activation='relu'))

#Add another dropout layer
model.add(tf.keras.layers.Dropout(0.25))


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [7]:
#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))


model.compile(optimizer='adam', 
              loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 28, 28, 1)         0         
_________________________________________________________________
batch_normalization (BatchNo (None, 28, 28, 1)         4         
_________________________________________________________________
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 9216)              0         
_________________________________________________________________
dense (Dense)                (None, 200)               1

In [10]:
#Train the model
model.fit(trainX,train,          
          validation_data=(testX,test),
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 72s 1ms/sample - loss: 0.3823 - accuracy: 0.8635 - val_loss: 0.2898 - val_accuracy: 0.8919
Epoch 2/10
60000/60000 [==============================] - 59s 990us/sample - loss: 0.2299 - accuracy: 0.9168 - val_loss: 0.2580 - val_accuracy: 0.9044
Epoch 3/10
60000/60000 [==============================] - 58s 970us/sample - loss: 0.1726 - accuracy: 0.9362 - val_loss: 0.2222 - val_accuracy: 0.9182
Epoch 4/10
60000/60000 [==============================] - 59s 987us/sample - loss: 0.1322 - accuracy: 0.9514 - val_loss: 0.2419 - val_accuracy: 0.9218
Epoch 5/10
60000/60000 [==============================] - 60s 1ms/sample - loss: 0.0993 - accuracy: 0.9623 - val_loss: 0.2670 - val_accuracy: 0.9230
Epoch 6/10
60000/60000 [==============================] - 62s 1ms/sample - loss: 0.0767 - accuracy: 0.9717 - val_loss: 0.3238 - val_accuracy: 0.9160
Epoch 7/10
60000/60000 [==========================

In [12]:
print ('Acuraccy on test set is found to be 92.23% on 10th itration ' )

Acuraccy on test set is found to be 92.23% on 10th itration 


In [13]:
print ('validation accuracy is 92.23%')

validation accuracy is 92.23%


In [17]:
test1 = tf.cast(testX, tf.float32)
print(confusion_matrix(model.predict_classes(test1), testY))

[[878   0  18  16   3   0  86   0   5   1]
 [  1 987   1   8   1   0   0   0   0   0]
 [ 13   0 853   8  34   0  27   0   0   0]
 [  8   7   6 903  15   0  19   0   4   0]
 [  1   2  58  32 879   0  43   0   0   0]
 [  1   0   0   0   0 986   0  11   1   4]
 [ 93   2  63  33  67   0 819   0   5   1]
 [  0   0   0   0   0   9   0 967   2  20]
 [  5   2   1   0   1   0   6   0 982   0]
 [  0   0   0   0   0   5   0  22   1 974]]


In [19]:
from sklearn.metrics import classification_report,confusion_matrix

print("Please find the classification report as following: \n")
print(classification_report(model.predict_classes(test1),testY))

Please find the classification report as following: 

              precision    recall  f1-score   support

           0       0.88      0.87      0.87      1007
           1       0.99      0.99      0.99       998
           2       0.85      0.91      0.88       935
           3       0.90      0.94      0.92       962
           4       0.88      0.87      0.87      1015
           5       0.99      0.98      0.98      1003
           6       0.82      0.76      0.79      1083
           7       0.97      0.97      0.97       998
           8       0.98      0.98      0.98       997
           9       0.97      0.97      0.97      1002

    accuracy                           0.92     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.92      0.92      0.92     10000

